# npm run build -- super-ttc::iosevka-custom
# cp dist/.super-ttc/iosevka-custom.ttc ~/.local/share/fonts
# fc-cache -fv

[collectPlans.iosevka-custom]
from = ["iosevka-custom"]

[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.iosevka-custom.variants]
inherits = "ss09"

[buildPlans.iosevka-custom.variants.design]
one = "no-base"
