# npm run build -- super-ttc::iosevka-custom
# cp dist/.super-ttc/iosevka-custom.ttc ~/.local/share/fonts
# fc-cache -fv

[collectPlans.iosevka-custom]
from = ["iosevka-custom"]

[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.iosevka-custom.variants]
inherits = "ss09"

[buildPlans.iosevka-custom.variants.design]
one = "no-base"

# NOTE: gnome-terminal font width granularity is too big? shape=525 is the same as shape=500.
# kitty,neovide,vscode render it correctly.
# It seems that gnome-terminal only allows some fixed combinations for the cell size.
[buildPlans.iosevka-custom.widths.normal]
shape = 525
menu = 5
css = "normal"
